name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set to your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  # Set the .NET version required for your project

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish --configuration Release --output publish

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: './publish'

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
